name: OscarIgnacioJimenez
favicon: null
layout_spectrum: 0.6876252482179552
typography_spectrum: 0.977643025573343
title: CINEMATOGRAPHY
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#887c62'
    - '#422a1e'
    - '#485251'
    - '#a09d7a'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
