name: OSCAR IGNACIO JIMENEZ
favicon: null
layout_spectrum: 0.6876252482179552
typography_spectrum: 0.977643025573343
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.869169486919418
  lightness: 0.14953808952122927
  saturation: 0.3755984124727547
  rhythmicContrast: 0.020661027869209647
purpose: []
